name: NodeJS with Next.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 23.6.1
      uses: actions/setup-node@v4
      with:
        node-version: '23.6.1'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build